### ISSUE TITLE
iOS binding

### ISSUE THREAD

**Issue by rodrigueslg** [msioen/ZXingObjC.Binding#1]
do you plan to create a iphone binding?

**Comment by msioen** [comment]
I'm planning to but probably won't be for the next few weeks. In the mean time you can check out https://github.com/Redth/ZXing.Net.Mobile which is an excellent ZXing 'variant' that does work on iOS.

**Comment by rodrigueslg** [comment]
Yeah, i already tried it, but the data matrix format quality is very slow on this plugin.

**Comment by msioen** [comment]
I had a look at the iOS binding and turns out the binding bits from the osX binding could be reused.
You can find it here: https://www.nuget.org/packages/ZXingObjC.iOS.Binding/
